### ISSUE TITLE
URL paths not pointing to files, 404 error

### ISSUE THREAD

**Issue by n-io** [dataspread/dataspread-web#250]
Hello,

Release 0.5 produces the following errors:

![image](https://user-images.githubusercontent.com/36768051/57473720-652bd180-7288-11e9-9961-12ed90fd9556.png)

For some reason, `DataSpread` is missing from the URL, e.g., it needs to point to `localhost:8080/DataSpread/manifest.json` to correctly find the `manifest.json` file. Editing the `index.html` appears to fix this, although the error will occur in various other places as well.

The error did not occur with an older version of DataSpread I had previously running (which is why I am not initially suspecting a problem with my setup). Also, the error occurs both for the pre-built .war file and for code built from trunk.

Please could you take a look and advise whether this needs a fix or whether a work-around exists?

Many thanks in advance!

**Comment by adityagp** [comment]
Thanks for letting us know. We'll look into it asap! 
Would you mind telling us what you're using DataSpread for?

**Comment by rahmansunny071** [comment]
In the new release, the correct URL for accessing DataSpread should be: http://localhost:8080/

We have updated the setup instruction to reflect the new change.

**Comment by rahmansunny071** [comment]
^resolved.

**Comment by cameronew** [comment]
Hi unfortunately this is still an issue with both WAR and source code.. Tomcat is design to have many application running in the instance so the URL is always http://localhost:8080/AppName i.e. http://localhost:8080/DataSpread
